// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzluhriqpzzafczybgst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6bHVocmlxcHp6YWZjenliZ3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTcyMzMsImV4cCI6MjA2NzczMzIzM30.qSuCPSTXCO7lhCfM9hDAHbCW02xfTe7W5q0MhvlO6oY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});