// QuickBooks Online Detail Type options organized by account type
export const QBO_DETAIL_TYPES: Record<string, string[]> = {
  asset: [
    'Bank',
    'Checking',
    'Savings',
    'Cash on Hand',
    'Money Market',
    'Payment Processor',
    'Accounts Receivable (A/R)',
    'Inventory',
    'Prepaid Expenses',
    'Employee Cash Advances',
    'Loans to Officers',
    'Loans to Employees',
    'Other Current Assets',
    'Undeposited Funds',
    'Furniture and Equipment',
    'Machinery and Equipment',
    'Vehicles',
    'Buildings',
    'Accumulated Depreciation',
    'Leasehold Improvements',
    'Other Fixed Assets',
    'Goodwill',
    'Intangible Assets',
    'Security Deposits',
    'Other Long-Term Assets'
  ],
  liability: [
    'Accounts Payable (A/P)',
    'Credit Card',
    'Sales Tax Payable',
    'Payroll Liabilities',
    'Customer Deposits',
    'Unearned Revenue',
    'Deferred Revenue',
    'Line of Credit',
    'Short Term Loans Payable',
    'Other Current Liabilities',
    'Notes Payable',
    'Loan Payable',
    'Other Long-Term Liabilities'
  ],
  equity: [
    'Owner\'s Equity',
    'Owner\'s Investment',
    'Owner\'s Draw',
    'Partner Contributions',
    'Partner Distributions',
    'Retained Earnings',
    'Opening Balance Equity',
    'Common Stock',
    'Preferred Stock',
    'Additional Paid-In Capital'
  ],
  revenue: [
    'Sales of Product Income',
    'Service/Fee Income',
    'Subscription Income',
    'Shipping Income',
    'Interest Income',
    'Other Investment Income',
    'Other Income'
  ],
  expense: [
    'Cost of Goods Sold',
    'Supplies and Materials - COGS',
    'Freight and Delivery - COGS',
    'Merchant Fees - COGS',
    'Advertising and Promotion',
    'Bank Charges',
    'Charitable Contributions',
    'Computer and Internet Expenses',
    'Contract Labor',
    'Dues and Subscriptions',
    'Education and Training',
    'Insurance',
    'Legal and Professional Fees',
    'Meals and Entertainment',
    'Office Supplies',
    'Payroll Expenses',
    'Rent or Lease Payments',
    'Repairs and Maintenance',
    'Software Subscriptions',
    'Telephone',
    'Travel',
    'Utilities',
    'Shipping and Delivery Expense',
    'Depreciation Expense',
    'Interest Paid',
    'Taxes - Licenses and Fees',
    'Miscellaneous Expense',
    'Other Business Expenses',
    'Other Income',
    'Interest Earned',
    'Dividend Income',
    'Other Expense',
    'Interest Expense',
    'Penalties and Settlements',
    'Loss on Asset Disposal'
  ]
};

// Get detail types for a specific account type
export const getDetailTypesForAccountType = (accountType: string): string[] => {
  return QBO_DETAIL_TYPES[accountType] || [];
};
